var aNavItemData = [
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p2.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		}					
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2',
			price:'3299',
			tag:'新品'
		}					
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p2.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		}					
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2',
			price:'3299',
			tag:'新品'
		}					
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p2.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		}					
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2',
			price:'3299',
			tag:'新品'
		}					
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p2.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		}					
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2',
			price:'3299',
			tag:'新品'
		}					
	]			
];

var aCateItemData = [
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},		
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},							
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p2.jpg',
			name:'小米MIX2'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p2.jpg',
			name:'小米MIX2'
		}		
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		}		
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p2.jpg',
			name:'小米MIX2'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p2.jpg',
			name:'小米MIX2'
		}		
	],	
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		}		
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p2.jpg',
			name:'小米MIX2'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p2.jpg',
			name:'小米MIX2'
		}		
	],	
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		}		
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p2.jpg',
			name:'小米MIX2'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p2.jpg',
			name:'小米MIX2'
		}		
	],	
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		}		
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p2.jpg',
			name:'小米MIX2'
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p2.jpg',
			name:'小米MIX2'
		}		
	],						
];

var aElecItemData = [
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p2.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			top:{
				url:'https://www.kuazhu.com',
				img:'images/ca.png',
				name:'小米MX2 8GB+128GB 黑b',
				price:'3699'
			},
			bottom:{
				url:'https://www.kuazhu.com',
				txt:'浏览更多',
				tag:'热门',
				icon:'&#xe615;'

			}
		}												
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p2.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			top:{
				url:'https://www.kuazhu.com',
				img:'images/ca.png',
				name:'小米MX2 8GB+128GB 黑b',
				price:'3699'
			},
			bottom:{
				url:'https://www.kuazhu.com',
				txt:'浏览更多',
				tag:'热门',
				icon:'&#xe615;'

			}
		}												
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p2.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			top:{
				url:'https://www.kuazhu.com',
				img:'images/ca.png',
				name:'小米MX2 8GB+128GB 黑b',
				price:'3699'
			},
			bottom:{
				url:'https://www.kuazhu.com',
				txt:'浏览更多',
				tag:'热门',
				icon:'&#xe615;'

			}
		}												
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p2.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			url:'https://www.kuazhu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbb',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是',
				author:'kauzhu'
			}
		},
		{
			top:{
				url:'https://www.kuazhu.com',
				img:'images/ca.png',
				name:'小米MX2 8GB+128GB 黑b',
				price:'3699'
			},
			bottom:{
				url:'https://www.kuazhu.com',
				txt:'浏览更多',
				tag:'热门',
				icon:'&#xe615;'

			}
		}												
	]
];